#ifndef NGN_VERSION_H
#define NGN_VERSION_H

#define NGN_FIRMWARE_VERSION "0.2.0-ngn002"
#define NGN_FIRMWARE_VERSION_MAJOR 0u
#define NGN_FIRMWARE_VERSION_MINOR 2u
#define NGN_FIRMWARE_VERSION_PATCH 0u
#define NGN_PROTOCOL_VERSION 1u

#endif
